server {
    listen 80;
    server_name api.toanhodev.com;

    include /etc/nginx/conf.d/snippets/acme.conf;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name api.toanhodev.com;

    include /etc/nginx/conf.d/snippets/ssl.conf;

    location / {
        proxy_pass http://api:3001;
        include /etc/nginx/conf.d/snippets/proxy.conf;
    }
}
