server {
    listen 80;
    server_name bo.toanhodev.com;

    include /etc/nginx/conf.d/snippets/acme.conf;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name bo.toanhodev.com;

    include /etc/nginx/conf.d/snippets/ssl.conf;

    location / {
        include /etc/nginx/conf.d/snippets/resolver.conf;
        set $upstream_bo bo;
        proxy_pass http://$upstream_bo:3002;
        include /etc/nginx/conf.d/snippets/proxy-bo.conf;
    }
}
