server {
    listen 80;
    server_name toanhodev.com www.toanhodev.com;

    include /etc/nginx/conf.d/snippets/acme.conf;

    location / {
        proxy_pass http://web:3000;
        include /etc/nginx/conf.d/snippets/proxy.conf;
    }
}
